Import the Journal Model (Class Library) and load economic journal as "ej"

In [2]:
import Models.JournalModel as JM
ej = JM.Journal("ej")

Check which volumes, years, issues we have

In [3]:
volumes = ej.list_volumes('list')
years = ej.list_years('list')

print(f"For {ej.name}, we have the following volumes: {volumes}")
print(f"these volumes span the following years respectively: {years}")

For Data/The Economic Journal, we have the following volumes: [113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]
these volumes span the following years respectively: [2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]


We can list the issues in a volume. Lets take volume 126

In [4]:
v = ej.volume(126)  # select volume 126
issues = v.list_issues('list')

print(f"In volume 126, we have the following issues: {issues}")

In volume 126, we have the following issues: [590, 591, 592, 593, 594, 595, 596, 597, 598]


let us select an issue and list the articles. Lets take issue 593

In [5]:
i = v.issue(593)
i.list_articles()

authors  \
id                                                      
1                 [Achyuta Adhvaryu, Anant Nyshadham]   
2    [İ. Semih Akçomak, Dinand Webbink, Bas ter Weel]   
3           [Yann Algan, Pierre Cahuc, Marc Sangnier]   
4                         [Stefan Ambec, Lars Ehlers]   
5                                 [Jeffrey V. Butler]   
6                 [Juan Carlos Córdoba, Marla Ripoll]   
7              [Christian Dustmann, Francesco Fasani]   
8   [Leopoldo Fergusson, James A. Robinson, Ragnar...   
9                          [Eric D. Gould, Omer Moav]   
10             [Grant D. Jacobsen, Dominic P. Parker]   
11     [Juanna Schrøter Joensen, Helena Skyt Nielsen]   
12                      [Edwin Leuven, Marte Rønning]   
13                                     [Sergey Nigai]   
14  [Gilles Saint‐Paul, Davide Ticchi, Andrea Vind...   
15                    [Jan C. van Ours, Ben Vollaard]   

                                                title  
id                                                     
1   Endowments at Birth and Parents’ Investments i...  
2   Why Did the Netherlands Develop So Early? The ...  
3   Trust and the Welfare State: The Twin Peaks Curve  
4          Regulation via the Polluter‐pays Principle  
5             Inequality and Relative Ability Beliefs  
6   Intergenerational Transfers and the Fertility–...  
7     The Effect of Local Area Crime on Mental Health  
8                                The Need for Enemies  
9   Does High Inequality Attract High Skilled Immi...  
10  The Economic Aftermath of Resource Booms: Evid...  
11  Mathematics and Gender: Heterogeneity in Cause...  
12  Classroom Grade Composition and Pupil Achievement  
13  On Measuring the Welfare Gains from Trade Unde...  
14                 A Theory of Political Entrenchment  
15  The Engine Immobiliser: A Non‐starter for Car ...

We can select an article easily from the issue object. Lets take article 3, about trust and the welfare state

In [13]:
a = i.article(5) # select article 3
a.list_headings()

heading_name
h1                               
1                    Introduction
2   1. Closely Related Literature
3                 2. Experiment 1
4                 3. Experiment 2
5           4. Concluding Remarks
6                       Footnotes
7                      References
8                    Author notes
9              Supplementary data

We can list all of the headings in the article with the method list_headings()

In [7]:
a.list_headings()

heading_name
h1                               
1                    Introduction
2   1. Closely Related Literature
3                 2. Experiment 1
4                 3. Experiment 2
5           4. Concluding Remarks
6                       Footnotes
7                      References
8                    Author notes
9              Supplementary data

We can also list all of the tables in the article by the method list_tables()

In [14]:
a.list_tables()

name                                              title
id                                                             
1    Table 1                     Summary of Experiment 1 Design
2    Table 2                   Actual Performance, Experiment 1
3    Table 3         Relative Performance Beliefs, Experiment 1
4    Table 4            Actual Task 1 Performance, Experiment 2
5    Table 5  Relative Task 1 Performance Beliefs, Ability‐i...
6    Table 6  Relative Task 1 Performance Beliefs, Effort‐in...
7    Table 7  Selecting Tournament Incentives for Task 2, Ab...
8    Table 8        Beliefs and Tournament Choice, Experiment 2
9    Table 9  Beliefs, Performance and Task 2 Valuations fro...
10  Table 10                 Earnings from Task 2, Experiment 2

We can select a table and view it in the console. Lets look at table 4

In [16]:
t = a.table(2)  # select table 4
t.df

Unnamed: 0_level_0   PI treatment               Control        
          Unnamed: 0_level_1 High‐pay group Low‐pay group    C‐HP    C‐LP
0  Number of correct guesses           6.54          6.69    6.63    6.81
1                         SE         (0.25)        (0.25)  (0.31)  (0.19)
2               Observations             41            42      33      36

We can extract all of the coefficients by the method list_coefficients()

In [17]:
t.list_coefficients()

coefficient  standard_error  row_id                   row_name  col_id  \
1         6.54            0.25       4  Number of correct guesses       1   
2         6.69            0.25       4  Number of correct guesses       2   
3         6.63            0.31       4  Number of correct guesses       3   
4         6.81            0.19       4  Number of correct guesses       4   

                      col_name  sig_stars    z_score        p_value  
1  PI treatment High‐pay group          0  26.160000  7.584223e-151  
2   PI treatment Low‐pay group          0  26.760000  9.445642e-158  
3                 Control C‐HP          0  21.387097  1.761889e-101  
4                 Control C‐LP          0  35.842105  2.441139e-281

If we want to look at the text in a specific section (under a specific heading) we select a heading and print the text attribute. Looking at the table of contents from the .list_headings() method above, let us look at the text in heading 1, the Introduction.

In [18]:
intro = a.heading(1)
intro.text

'What causes inequality to persist? This question is of perennial interest to economists both because of its implications for efficiency – underdeveloped or underutilised human capital may translate into forgone productivity – as well as on more general moral grounds. Given its long pedigree as a puzzle of interest, the literature on persistent inequality is large and offers many compelling theoretical explanations which can be grouped into a few broad categories (Piketty, 2000). One familiar category of explanations singles out the importance of external factors such as real or expected discrimination (Becker, 1971; Arrow, 1971) or access to credit markets upon which investment in human or physical capital depends (Loury, 1981; Banerjee and Newman, 1991,1993; Galor and Zeira, 1993; Torvik, 1993; Gaviria, 2002). A second category offers as a primary explanation differences in the distribution of individual traits or preferences, for example, risk tolerance, a preference for competition

If we want to look at the abstract instead, we can access the abstract directly from the article object.

In [11]:
a.abstract

'We show the existence of a twin peaks relation between trust and the size of the welfare state that stems from two opposing forces. Uncivic people support large welfare states because they expect to benefit from them without bearing their costs. But civic individuals support generous benefits and high taxes only when they are surrounded by trustworthy individuals. We provide empirical evidence for these behaviours and this twin peaks relation in the OECD countries.'

Article objects have other data stored in them as well. Authors, author count, doi link, etc.

In [12]:
print(f"The article title is {a.title}")
print(f"The authors are {a.authors}")
print(f"The number of authors are {a.author_count}")
print(f"The article's doi is: {a.doi}")

The article title is Trust and the Welfare State: The Twin Peaks Curve
The authors are ['Yann Algan', 'Pierre Cahuc', 'Marc Sangnier']
The number of authors are 3
The article's doi is: https://doi.org/10.1111/ecoj.12278


For a final comment, we can access an article directly by doi, instead of going through volume and issue. We can access the same article by its doi

In [13]:
a2 = ej.find_article_by_doi(a.doi)  # access the article from the ej object by doi
a.title == a2.title # confirm that it is the same article

True